### ISSUE TITLE
Can't render your qmd file!

### ISSUE THREAD

**Issue by donotdespair** [NhuPham254/mcxs24-Research-Forecasting#2]
Hey @NhuPham254 

How are you? May I ask you for help? I can't render your `index.qmd` file and receive the following mesage:
```
Quitting from lines 135-169 [unnamed-chunk-4] (index.qmd)
Error in `if (abs_data$frequency == "Quarterly") ...`:
! the condition has length > 1
Backtrace:
 1. global process_abs_data("A84423130A", start_date, end_date)
                                                                                                            
Execution halted
```
Is the file rendering properly on your side? Can you have a look at that and let me know how this goes? I'd rather work with a version I can compile. I hope we can find solution here. Let me know in an answer in this issue by tagging me @donotdespair

Thank you, T

**Comment by NhuPham254** [comment]
Hi Tomasz @donotdespair ,

I have downloaded the old index.qmd version (I am assuming the qmd version that was submitted for Proposal) and the render works for me, I can see the website normally.

I am not sure what the error above comes from.

**Comment by donotdespair** [comment]
Thanks! And what about the current version?

**Comment by NhuPham254** [comment]
Hi @donotdespair,
I have done some editing since to make the code less repetitive, the current version of index.qmd renders normally for me as well.

**Comment by donotdespair** [comment]
OK, it still doesn't work for me, but I managed to read your proposal and grade it. Would you please have a look at this? Do you have the newest RStudio and R? Have you updated the packages by running `update.packages()`? We have slightly different environments we work in and some of the things you do, don't work at my side.

Greetings, T
